### ISSUE TITLE
Add `run_exports`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/libblst-feedstock#2]
Currently this package is missing [`run_exports`]( https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#export-runtime-requirements ). It would be good to add that with an appropriate version constraint

Edit - Also would recommend adding this to global pinnings so migrations are handled correctly: https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/6623

**Comment by step21** [comment]
Fine with me. Though docs could really use some work, they just talk about adding `run_exports` but don't give an example. conda.io docs were more helpful.
So I assume you want sth like?

```
run_exports:
    - {{ pin_subpackage('libblst', max_pin='0.3.x') }}
```

If all 0.3.x are actually ABI compatible I am not sure though. So far 0.3.13 is the only version anyway.

**Comment by MementoRC** [comment]
I initially created the recipe with versioning and run_exports but was asked to simplify it. Do you mean that I should create a `libblst.so.x.x.x` and the associated `libblst-{{ so_major }}`?

**Comment by jakirkham** [comment]
> ...they just talk about adding `run_exports` but don't give an example

Like this example?

> For example, you may use [Pinning expressions](https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#pinning-expressions) to obtain flexible version pinning relative to versions present at build time:
> 
> ```yaml
> build:
>   run_exports:
>     - {{ pin_subpackage('libpng', max_pin='x.x') }}
> ```
> 
> With this example, if libpng were version 1.6.34, this pinning expression would evaluate to `>=1.6.34,<1.7`.

The docs live [here]( https://github.com/conda/conda-build/blob/e4eed5c9d8c9b3ad0e2949289de1a73cce561766/docs/source/resources/define-metadata.rst#export-runtime-requirements ). Please feel free to raise a new issue or PR with feedback

**Comment by jakirkham** [comment]
> I initially created the recipe with versioning and run_exports but was asked to simplify it. Do you mean that I should create a `libblst.so.x.x.x` and the associated `libblst-{{ so_major }}`?

Think the PR ( https://github.com/conda-forge/libblst-feedstock/pull/3 ) looks reasonable

**Comment by step21** [comment]
> > ...they just talk about adding `run_exports` but don't give an example
> 
> Like this example?
> 

I was referring to this part: https://conda-forge.org/docs/maintainer/pinning_deps/?highlight=run_exports#specifying-run_exports
But ok if it's mentioned somewhere else it's fine.

**Comment by jakirkham** [comment]
Ah had included the former in the OP link of the issue. So assumed that was what we were talking about

There have been discussions over the years about not repeating the conda & conda-build docs in conda-forge. So what we have is more minimal. Perhaps we could add more links there

**Comment by MementoRC** [comment]
@jakirkham While we have your attention, I was under the impression that github: source build (when there is a Release/Tag) were preferred to PyPI sourced build, am I in error? I systematically go directly to the github when creating staged recipe, often not checking pypi, but for naming convention

**Comment by step21** [comment]
Small question @MementoRC as you put run_exports pinned package as `x.x`, will it just match on everything?
https://github.com/conda-forge/libblst-feedstock/pull/3/files

**Comment by jakirkham** [comment]
> While we have your attention, I was under the impression that github: source build (when there is a Release/Tag) were preferred to PyPI sourced build, am I in error? I systematically go directly to the github when creating staged recipe, often not checking pypi, but for naming convention

Personally prefer PyPI as it provides artifacts with stable checksums. GitHub releases don't provide this (at least not without additional effort by project maintainers)

**Comment by MementoRC** [comment]
Do you mean for the `headers` sub-package? from what I understand the pin is only needed for the dynamic library, I could just make one output, I originally had a -devel, -so_major and -headers. When I removed the -so_major, I felt lazy to have to remove the `ouputs`, as well as personal preference for the flexibility of selecting what goes into the package, this recipe builds a static library, that shouldn't be included

**Comment by step21** [comment]
> Small question [@MementoRC](https://github.com/MementoRC) as you put run_exports pinned package as `x.x`, will it just match on everything? https://github.com/conda-forge/libblst-feedstock/pull/3/files

Please disregard, seems I still didn't know how this worked.

**Comment by MementoRC** [comment]
> 
> Personally prefer PyPI as it provides artifacts with stable checksums. GitHub releases don't provide this (at least not without additional effort by project maintainers)

The sha256sum? I guess I was influenced by my first recipe where the PyPI did not include the license, nor the package tests - github feels less 'man-in-the-middle'

I guess, unless, strongly reprimanded, I will have a tendency to prefer github - I tried using a commit hash once (because it'll never change), but it seemed to be an even bigger no-no

Suddenly wondering, does using github slows the rate of `staged-recipe` review o.0? several of my recent proposals have been idling for an uncommon long time and my honeymoon with Uwe seems to also be short-lived :,(

**Comment by MementoRC** [comment]
> 
> Please disregard, seems I still didn't know how this worked.

TBH, me neither, possibly even less ... lol

**Comment by jakirkham** [comment]
> Do you mean for the `headers` sub-package? from what I understand the pin is only needed for the dynamic library, I could just make one output, I originally had a -devel, -so_major and -headers. When I removed the -so_major, I felt lazy to have to remove the `ouputs`, as well as personal preference for the flexibility of selecting what goes into the package, this recipe builds a static library, that shouldn't be included

This is a reasonable question. Naively would have thought we would have thought the packages would be...

* `libblst` - shared objects only
* `libblst-devel` - depends on `libblst` and adds headers + build config files (like `.pc` + `FindBlst.cmake` or similar)

The `libblst-devel` would then have `run_exports` to add `libblst`

That said, don't know as much about this library. So there may be reasons for carving up the way it is that I'm not aware of

**Comment by MementoRC** [comment]
@xhochy Did I mis-understand your review (not sure whether it is this recipe or another) where I was implementing the scheme above and you mentioned a simpler scheme was preferred?

This is my de-facto scheme for any C/C++ lib package that I work on,, sometimes the recipe requires so pretty big butchering of upstream, when they don't naturally implement the lib versioning

To clarify, I just want to know which scheme to use and when ... quite confused (especially given that I had done the work, this lib did not implement the versioning upstream)

A more proactive question, should I implement it for this feedstock (it should not be too difficult to pull up my old notes)

**Comment by xhochy** [comment]
I agree with the scheme that @jakirkham posted. I don't remember the particular review, but we mostly use the `-headers` suffix if something ships a header-only part, i.e. if you only use things from these headers, you don't need the shared library at runtime.

**Comment by MementoRC** [comment]
Thanks for the feedback. I am pretty sure I don't quite get it yet ... and likely will implement the wrong scheme in future recipes, just point me in the right direction when I do - For this recipe, should I separate?

Currently, my limited understanding is that, if you use the headers, you define things related to that library in your binary so will most likely need the runtime lib - unless it's a header only library like I saw in boost? To me, it looks like a difficult thing to assess

**Comment by xhochy** [comment]
>  For this recipe, should I separate?

If you are unsure, probably not.

**Comment by MementoRC** [comment]
@xhochy Do you have any comments on the way I interact with conda-forge? Could some (or most?) of what I do be considered obnoxious? You did say a few good things for some of my PRs, so an honest feedback would be welcome, suggestions as to how to improve/reduce/limit as well.
